<?php

namespace ContainerZSpJFIk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SM4AUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._sM4A_u' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\PokeController::index' => ['privates', '.service_locator.XKw4cjg.App\\Controller\\PokeController::index()', 'getPokeControllerindexService', true],
            'App\\Controller\\PokeController::add' => ['privates', '.service_locator.cCrKU7g.App\\Controller\\PokeController::add()', 'getPokeControlleraddService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\PokeController:index' => ['privates', '.service_locator.XKw4cjg.App\\Controller\\PokeController::index()', 'getPokeControllerindexService', true],
            'App\\Controller\\PokeController:add' => ['privates', '.service_locator.cCrKU7g.App\\Controller\\PokeController::add()', 'getPokeControlleraddService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\PokeController::index' => '?',
            'App\\Controller\\PokeController::add' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\PokeController:index' => '?',
            'App\\Controller\\PokeController:add' => '?',
        ]);

        if (isset($container->privates['.service_locator._sM4A_u'])) {
            return $container->privates['.service_locator._sM4A_u'];
        }

        return $container->privates['.service_locator._sM4A_u'] = $instance;
    }
}
