<?php

namespace ContainerZSpJFIk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPokedexTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\PokedexType' shared autowired service.
     *
     * @return \App\Form\PokedexType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/PokedexType.php';

        return $container->privates['App\\Form\\PokedexType'] = new \App\Form\PokedexType();
    }
}
