<?php

namespace ContainerBIh4R7r;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPokeControlleraddService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cCrKU7g.App\Controller\PokeController::add()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'pokedexRepository' => ['privates', 'App\\Repository\\PokedexRepository', 'getPokedexRepositoryService', true],
        ], [
            'entityManager' => '?',
            'pokedexRepository' => 'App\\Repository\\PokedexRepository',
        ]))->withContext('App\\Controller\\PokeController::add()', $container);

        if (isset($container->privates['.service_locator.cCrKU7g.App\\Controller\\PokeController::add()'])) {
            return $container->privates['.service_locator.cCrKU7g.App\\Controller\\PokeController::add()'];
        }

        return $container->privates['.service_locator.cCrKU7g.App\\Controller\\PokeController::add()'] = $instance;
    }
}
