<?php

namespace ContainerBIh4R7r;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPokeControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XKw4cjg.App\Controller\PokeController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XKw4cjg.App\\Controller\\PokeController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pokedexRepository' => ['privates', 'App\\Repository\\PokedexRepository', 'getPokedexRepositoryService', true],
        ], [
            'pokedexRepository' => 'App\\Repository\\PokedexRepository',
        ]))->withContext('App\\Controller\\PokeController::index()', $container);
    }
}
