<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZSpJFIk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZSpJFIk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZSpJFIk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZSpJFIk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZSpJFIk\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZSpJFIk',
    'container.build_id' => '8428cb79',
    'container.build_time' => 1776844089,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZSpJFIk');
